apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv-0
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/mongo-0
