apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-creds
  namespace: default
spec:
  encryptedData:
    password: AgB2YPR2g3NtWubJW103kxhZPORhvetRWgjWF47zKKBDuognGksWodKhN6Pf8/Bse5fWY7a42bpltfotoytxeAQC4wNT3D9szkmGkTyg/WinPUHNPNoYADzCcGQR4Ts/ZEJIatf5Tu9HFgDChlmnf8pJjPQgaKVhmjLlP1LNlRzvfBx+AKk2WuFp+ZUv++oQWRVTM0OMHpedMAXzs+Pdx0UYPybeAclvubXRlDu2gkYo+JahXvO4ts9ufih+eupvmSnGd4P+KPpX5OnuaLdzuhOhJY/kSRYpj/5uTgVYv8lARxFEmMd1kBtGPI+VHu13M2ZJtj0Zm9R5Oy6uu7lAaSK7EHopj8N6uwcyzMvAWayrIv1tRQedwJa3UybqlnEFOiKAngpGxpupVyrpzAlbGvahmd72SumWOwKSoOxucct3xlIL79+93euDG77iID1qR3HfS1IKMYlRsfCzW+4+AmM2l5FoXIJniaaj/X+AhJMxNMQYK0a0iypxTNXneSviwX+f2x2naKjtDkeYyWQjDsuOFi/MU/1u5UQGQxqMdx3sQZLqD4m64Wqoe49PXNM6I6xPCNNaYHGZZiwkrQTToE+ky2M8MyanBoJOntsDdiZ01D4D0Rmw2OnDA4AOdeTJmApWMBAyBNDXltcaYyQcKOtSvekRyeL/egM60qFpEFSuYAWPQ/qd1rj9NKMu5XtSTNpnFekbnT7/FwiE5Eo=
    username: AgAg2iOFZ8/RyyLt9/D8zGkR0owQQqEpnL9pLB7UITUVL5/hjWfYO2SaB8Aus60VhPRQqSXsvnzPDPQVzy1roGEP9bwsl65qLs+ZBEZj8dlwGa42JvTW5QH4Afjd2+PyolrdNCLvKoW7GzmtLYfKcZ0brIkTWUn0gC9lwA6LpWlwfTZnuOUcz0qn1x7RWWyDCfOYy/5jLbbIN/uoLj/sELij0S3ite+/txHd7/TyoXMqe8OS1WGM7fudazP4od+W1h6aTCjNXJRoDmnWyu/uN/TmK1MrFHXJn0yZWWV6/cSOI5JEbw3TIxkH0AxSiNAFrOBDWBE0Pi74h5CR0TOoW6jOC59aSek/Hqk4Hu1Fgu1j6bBOS3E7MH3bfPygBPuznq9FN/t75z0OEu8TjXgD88E5k5tTVQa9Q7EglFjIGJxyqv1IKSPF5eE1Dmcpbv5VLQjTfLJjURQsenjenoeabweldD3k/CRWT8iopRdwr6FmIqdH7mBl+9/agDnFvjQ4VR6aNSCbjj6c11lcInWYhijg3Y2mwQU0WmOc8r2VgwkMxDXh2ZGoaQzUlOiUEfAQoFEs3ti8Z/ASInJy5oPOpWpXQl4qSnJbVxhJcyjU/owmStk19WExT35Y5MQyRYTNlWlmDJ0vYaZ+CQIRB1T6LYEPTigRODMeu6l2W43Np+d2z4Qv6SAOVPDEqBDpYfKr0eURJwE+zw==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-creds
      namespace: default
